
import React from 'react';
import CTAButton from '../shared/CTAButton';
import { ArrowUpRight, TrendingUp, Users, Award, Shield } from 'lucide-react';

const Metrics = () => {
  const stats = [
    {
      icon: TrendingUp,
      value: "$100M+",
      label: "Trading Profits Generated",
      description: "Total profits generated by our community members using our strategies."
    },
    {
      icon: Users,
      value: "1,000+",
      label: "Active Community Members",
      description: "Traders from over 50 countries actively participating in our exclusive community."
    },
    {
      icon: Award,
      value: "92%",
      label: "Success Rate",
      description: "Percentage of members who achieve profitability within 90 days of joining."
    },
    {
      icon: Shield,
      value: "7+ Years",
      label: "Market Experience",
      description: "Years of proven trading performance through all market conditions and cycles."
    }
  ];

  return (
    <section className="py-20 bg-black relative">
      {/* Background pattern */}
      <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAiIGhlaWdodD0iNjAiIHZpZXdCb3g9IjAgMCA2MCA2MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48ZyBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPjxnIGZpbGw9IiMzMzMiIGZpbGwtb3BhY2l0eT0iMC4wNSI+PHBhdGggZD0iTTM2IDM0aDR2MWgtNHYtMXptMC0yaDF2NGgtMXYtNHptMi0yaDF2MWgtMXYtMXptLTIgMmgxdjFoLTF2LTF6bS0yLTJoMXYxaC0xdi0xem0yLTJoMXYxaC0xVjI4em0tMiAyaDF2MWgtMXYtMXptLTItMmgxdjFoLTF2LTF6TTM0IDI4aDR2MWgtNHYtMXptMCAwaDR2NGgtNHYtNHptMiAyaC0ydjJoMnYtMnoiLz48L2c+PC9nPjwvc3ZnPg==')] opacity-10"></div>
      <div className="absolute top-0 left-0 w-full h-px bg-gradient-to-r from-transparent via-blkr-gold/30 to-transparent"></div>
      
      <div className="container-custom relative z-10">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-playfair font-bold mb-4">
            The <span className="text-blkr-gold">Numbers</span> Don't Lie
          </h2>
          <p className="text-gray-400 max-w-2xl mx-auto">
            Our community's performance speaks for itself. These are the results our members achieve with BLKR Trading strategies.
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {stats.map((stat, index) => (
            <div 
              key={index} 
              className="bg-gray-900/20 backdrop-blur-sm border border-gray-800 rounded-lg p-6 hover:border-blkr-gold/50 transition-all duration-300 animate-fade-in"
              style={{ animationDelay: `${index * 0.1}s` }}
            >
              <div className="flex justify-between items-start mb-4">
                <div className="p-2 bg-blkr-gold/10 rounded-lg">
                  <stat.icon className="w-6 h-6 text-blkr-gold" />
                </div>
                <ArrowUpRight className="w-5 h-5 text-blkr-gold/70" />
              </div>
              <div className="text-3xl font-bold text-white mb-1">{stat.value}</div>
              <div className="text-sm font-medium text-blkr-gold mb-2">{stat.label}</div>
              <p className="text-sm text-gray-400">{stat.description}</p>
            </div>
          ))}
        </div>
        
        {/* CTA Section */}
        <div className="mt-16 bg-gradient-to-r from-gray-900 to-black border border-gray-800 rounded-lg p-8 md:p-10">
          <div className="flex flex-col md:flex-row items-center justify-between gap-6">
            <div>
              <h3 className="text-2xl md:text-3xl font-playfair font-bold mb-2">Ready to join the elite traders?</h3>
              <p className="text-gray-400">Take the first step toward transforming your trading career today.</p>
            </div>
            <CTAButton size="lg" withArrow>
              Apply for Membership
            </CTAButton>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Metrics;
